[package]
name = "simple-twine-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]

anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }

[[example]]

name = "print"

